In [1]:
import pandas as pd

df_gemini = pd.read_parquet('./data/results/gemini_results.parquet')
df_gemini

google/gemini-2.5-pro-preview-03-25       1st       2nd       3rd       4th
property
bioActivity                          0.770816  0.781151  0.798830  0.811696
collectionSite                       0.711140  0.710986  0.731430  0.710494
collectionSpecie                     0.959948  0.963554  0.961121  0.952727
collectionType                       0.949517  0.951189  0.949262  0.953704
name                                 0.891757  0.891531  0.875618  0.882479

In [2]:
df_gpt = pd.read_parquet('./data/results/openai_results.parquet')
df_gpt

openai/gpt-4.1         1st       2nd       3rd       4th
property
bioActivity       0.771510  0.784425  0.804678  0.809942
collectionSite    0.714786  0.716604  0.721915  0.727778
collectionSpecie  0.929802  0.924447  0.923146  0.900000
collectionType    0.956541  0.959950  0.964022  0.972222
name              0.647945  0.651971  0.620665  0.622329

In [3]:
df_ensemble = pd.read_parquet('./data/results/ensemble_results.parquet')
df_ensemble

ensemble               1st       2nd       3rd       4th
property
bioActivity       0.805787  0.815079  0.830409  0.830994
collectionSite    0.763342  0.764045  0.770718  0.766667
collectionSpecie  0.971146  0.969902  0.966546  0.954545
collectionType    0.956541  0.959950  0.964022  0.972222
name              0.921033  0.918350  0.904531  0.904380